### ISSUE TITLE
Compatible with `remark-slug` version 5

### ISSUE THREAD

**Issue by imcuttle** [remarkjs/remark-autolink-headings#42]
The related issue: https://github.com/remarkjs/remark-slug/issues/9

**Comment by jimthedev** [comment]
@wooorm Is there any chance we can hard fork this repo into Remark proper to get some merges? Specifically there are already [two forks](https://github.com/ben-eb/remark-autolink-headings/pull/41) so it might be good to just bring it in and give those people merge access? Thoughts?

**Comment by wooorm** [comment]
Finally compatible now!
