### ISSUE TITLE
Bug: version 5.0.0 on npm is outdated

### ISSUE THREAD

**Issue by imcuttle** [remarkjs/remark-autolink-headings#43]
remark-autolink-headings@5.0.0 in npm

- `dist/index.js`
```javascript
var base = function base(node, callback) {
    var data = node.data;

    if (!data || !data.htmlAttributes || !data.htmlAttributes.id) {
        return;
    }

    return callback('#' + data.htmlAttributes.id);
};
```

It's still `htmlAttributes` instead of `hProperties` in `src/index.js`
https://github.com/remarkjs/remark-autolink-headings/blob/bab44a06a5ce02b68edc8dbfe1493f59643bf543/src/index.js#L34

**Comment by imcuttle** [comment]
more information here #40

**Comment by wooorm** [comment]
@imcuttle We don’t have access to the npm package yet. Ben’s taking a break from OSS so I’m not bugging him too much, but just a little once in a while!

**Comment by wooorm** [comment]
Fixed!
