### ISSUE TITLE
`behaviour` doesn't follow American spelling standards

### ISSUE THREAD

**Issue by missmatsuko** [remarkjs/remark-autolink-headings#46]
['behavior' (without the 'u') is the American spelling of 'behaviour'](https://grammarist.com/spelling/behavior-behaviour/).

Usually code uses American spelling (e.g. `color`, not `colour`), but I'm not sure if it was an intentional choice to not use American spelling?

**Comment by Murderlon** [comment]
As far as I know the remark ecosystem leans towards American spelling but at this point I don't think it's worth the breaking change.

**Comment by wooorm** [comment]
I personally prefer British spelling, and use that in documentation. I do use US spelling for code though. Above all consistency is most important. The reason for this API case is that this library was originally authored by a UK citizen.

I think `behavior` would be better here. Although I’m very much against unneeded breaking changes, we can:

* Update the docs to use `behavior`
* Update the code to use `behavior` but fall back to `behaviour` if `behavior` is not given
* Cut a minor release

**Comment by missmatsuko** [comment]
Agreed! I can work on this, if you'd like. 

Should we also add some kind of warning when `behaviour` is used? 
If so, is `console.warn(someMessage)` sufficient? I don't know what's standard.

**Comment by ChristianMurphy** [comment]
Sounds good, Node does something similar ([docs](https://nodejs.org/api/util.html#util_util_deprecate_fn_msg_code) and [source](https://github.com/nodejs/node/blob/29d3d1ea135c5d5692c3fcd9fb9091efa1db5760/lib/internal/util.js#L44-L84))
`console.warn` looks like a nice, light weight approach :+1:  [(browser compatibility)](https://developer.mozilla.org/en-US/docs/Web/API/console#Browser_compatibility)

**Comment by wooorm** [comment]
Console.warn is nice enough but I'd still be slightly annoyed by those appearing from a minor update?
I would Def be for a comment that says something like 'remove next major'.

But I'm up for what everyone else things, no strong feelings!
