### ISSUE TITLE
latin char id link problem

### ISSUE THREAD

**Issue by ftpyz** [remarkjs/remark-autolink-headings#52]
in my language charter ş,iü,ğ ex. latin char not translate #id link .maybe use slugify package for address solved the problem

**Comment by wooorm** [comment]
We do use a slugging package, and adhere strictly to how github slugs headings.

Could you expand more on your question? You removed the issue template and that really helps us help you.

**Comment by ftpyz** [comment]
example my heading "Türkçe Bir Başlık" remark-autho-heading plugin change id anchor to "türkçe-bir-başlik". But browser can't go to this slug i use gridsome starter project go to example project
https://5ed5142a02b1495ea2b58fb6--admiring-cray-9266c6.netlify.app/getting-started left bar click "Türkçe Bir Başlık" cant go to anchor

https://github.com/ftpyz/jamdocs 

i hope i can tell

i fork your project add support slugify for anchor https://github.com/ftpyz/remark-autolink-headings/blob/master/src/index.js 

running example https://docs.gurmewoo.com/iyzibazaar-plus-yardim

**Comment by wooorm** [comment]
Sounds like: https://github.com/remarkjs/remark-slug/issues/12#issuecomment-636891539 maybe

**Comment by wooorm** [comment]
We already allow existing IDs if other tools add them: https://github.com/remarkjs/remark-autolink-headings/blob/b7cf0af89450c0d9ad38d374698e6b0883418253/src/index.js#L50

This is a problem with other tools in your stack: Vue, Gridsome, etc.
