### ISSUE TITLE
Generated link anchor doesn't have an icon

### ISSUE THREAD

**Issue by mhatvan** [remarkjs/remark-autolink-headings#54]
### Subject of the issue

The generated link doesn't have any link icon and zero width when it gets appended/prepended to the heading.

So the DOM is technically correct, but there is no way to click for the user to jump to the selected anchor.

Are we supposed to add a link icon ourselves and attach it to the .link.icon class on the span element?

### Expected behaviour

Nice link icon to click

### Actual behaviour

Unclickable anchor link

**Comment by ChristianMurphy** [comment]
> The generated link doesn't have any link icon and zero width when it gets appended/prepended to the heading.
> So the DOM is technically correct

The DOM is valid.
It adds a link tag to the document.

If you want to change the visual presentation, you can using https://github.com/remarkjs/remark-autolink-headings#optionscontent

> Are we supposed to add a link icon ourselves and attach it to the .link.icon class on the span element?

That is another approach, an alternative is https://github.com/remarkjs/remark-autolink-headings#optionscontent
